TRAIN:
    
    # Architecture name, see pytorch models package for
    # a list of possible architectures
    arch: 'resnet50'


    # SGD paramters
    lr: 0.1
    momentum: 0.9
    weight_decay: 0.0001

    # Print frequency, is used for both training and testing
    print_freq: 10

    # Dataset mean and std used for data normalization
    mean: !!python/tuple [0.485, 0.456, 0.406]
    std: !!python/tuple [0.229, 0.224, 0.225]

    # FAST ADVERSARIAL TRAINING PARAMETER

    # Starting epoch (interpret as multiplied by n_repeats)
    # start_epoch: 12
    # # Number of training epochs
    # epochs: 24

    # lr_epochs: !!python/tuple [12,22,25]
    # lr_values: !!python/tuple [0.4375,0.04375,0.004375]

    # Starting epoch (interpret as multiplied by n_repeats)
    start_epoch: 6
    # Number of training epochs
    epochs: 12

    lr_epochs: !!python/tuple [6,12]
    lr_values: !!python/tuple [0.04,0.004]

    # lr_epochs: !!python/tuple [6,7,12]
    # lr_values: !!python/tuple [0,0.1,0.01]

    # epochs: 18
    # lr_epochs: !!python/tuple [6,12,16,18]
    # lr_values: !!python/tuple [0.1,0.01,0.001,0]

    half: true
    random_init: true
    
DATA:
    # Number of data workers
    workers: 16

    # Color value range
    max_color_value: 255.0

    # FAST ADVERSARIAL TRAINING PARAMETER

    # Training batch size
    batch_size: 224

    # Crop Size for data augmentation
    crop_size: 224

# Defense
defense: FFX
block_size: 4
height: 224
width: 224
password: password
