TRAIN:
    
    # Architecture name, see pytorch models package for
    # a list of possible architectures
    arch: 'resnet50'

    # SGD paramters
    lr: 0.1
    momentum: 0.9
    weight_decay: 0.0001

    # Print frequency, is used for both training and testing
    print_freq: 10

    # Dataset mean and std used for data normalization
    mean: !!python/tuple [0.485, 0.456, 0.406]
    std: !!python/tuple [0.229, 0.224, 0.225]

    # Starting epoch (interpret as multiplied by n_repeats)
    start_epoch: 0

    # Number of training epochs
    epochs: 6

    lr_epochs: !!python/tuple [0,1,6]
    lr_values: !!python/tuple [0,0.4,0.04]

    half: true
    random_init: true
    
DATA:
    # Number of data workers
    workers: 16

    # Color value range
    max_color_value: 255.0

    # Training batch size
    batch_size: 512

    # Crop Size for data augmentation
    crop_size: 128

# Defense
defense: FFX
block_size: 4
height: 128
width: 128
password: password
